name: Clean Up Empty Lines on Issue

on:
  issues:
    types: [bracket]

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clean up empty lines
      run: |
        find . -type f -name "*.cs" -exec sed -i '' -E 's/{\s*$//g' {} \;
        find . -type f -name "*.cs" -exec sed -i '' -E 's/^\s*}$/}/g' {} \;

    - name: Commit changes
      run: |
        git add '*.cs'
        git commit -m "Clean up empty lines"
        git push origin test-remove-blank-lines
